"$schema" = 'https://starship.rs/config-schema.json'

right_format = """$time"""
command_timeout = 3600

add_newline = true

[directory]
truncation_length = 5

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[!](bold red)"

[time]
disabled = false
style = "dimmed white"
format = "[$time]($style)"

[git_status]
diverged = '↑$ahead_count↓$behind_count'
conflicted = '$count'
ahead = "[⇡${count}](yellow)"
behind = "[⇣${count}](blue)"
modified = "[!](yellow)"
untracked = "[?](bold cyan)"
