name: linter
on:
  pull_request: ~
  push: ~
permissions:
  contents: read
  statuses: write
jobs:
  linter:
    name: super linter
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: run linter
        uses: super-linter/super-linter/slim@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_CSS: false
